# Generated by Django 4.2.5 on 2023-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2002-04-20'),
            preserve_default=False,
        ),
    ]
